# Generated by Django 5.2.8 on 2025-11-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField()),
                ('content', models.TextField(help_text='Detailed content for the service page')),
                ('image', models.ImageField(help_text='Recommended size: 800x600px', upload_to='services/')),
                ('icon', models.CharField(blank=True, help_text="Font Awesome icon class (e.g., 'fas fa-wrench')", max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Higher number appears first')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-display_order', 'title'],
            },
        ),
    ]
