# Generated by Django 5.2.8 on 2025-11-30 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main heading for the About Us page', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Subheading or tagline', max_length=300)),
                ('content', models.TextField(help_text='Main content of the About Us section')),
                ('image', models.ImageField(blank=True, help_text='Main image for the About Us section', null=True, upload_to='about/')),
                ('mission', models.TextField(blank=True, help_text='Company mission statement')),
                ('values', models.TextField(blank=True, help_text='Company values (one per line)')),
                ('years_experience', models.PositiveIntegerField(default=0, help_text='Number of years in business')),
                ('projects_completed', models.PositiveIntegerField(default=0, help_text='Number of projects completed')),
                ('is_active', models.BooleanField(default=True, help_text='Set to False to hide this section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which team members are displayed')),
                ('is_active', models.BooleanField(default=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='website.aboutus')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
